{% set name = "qibo" %}
{% set version = "0.1.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibo/archive/v{{ version }}.tar.gz
  sha256: 3181822c8ebd11b83e6c498fea4ee7b2a1be13f6d1727d4da030ac7b3298b303

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - poetry
  run:
    - cma
    - numpy
    - joblib
    - matplotlib-base
    - psutil
    - python >=3.8
    - scipy
    - sympy
    - tabulate

test:
  imports:
    - qibo

about:
  home: https://github.com/qiboteam/qibo
  summary: A framework for quantum computing with hardware acceleration.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
