{% set name = "qibo" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibo/archive/v{{ version }}.tar.gz
  sha256: c38d1131e0109c1b42390b92238385ab12facfa27381c56cfa1498aae6ef1904

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cma
    - joblib
    - matplotlib-base
    - psutil
    - python >=3.7
    - pyyaml
    - scipy
    - sympy
    - importlib_metadata

test:
  imports:
    - qibo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qiboteam/qibo
  summary: A framework for quantum computing with hardware acceleration.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
