{% set name = "qibo" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibo/archive/v{{ version }}.tar.gz
  sha256: ebd4a69394a86173225f79bf6a30887837f94b865d49fa11c1e61f3db7abcd16

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - poetry
  run:
    - cma
    - numpy
    - joblib
    - matplotlib-base
    - psutil
    - python >=3.8
    - scipy
    - sympy
    - tabulate

test:
  imports:
    - qibo

about:
  home: https://github.com/qiboteam/qibo
  summary: A framework for quantum computing with hardware acceleration.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
